apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      containers:
      - name: my-nextjs-app
        # 이 부분을 GitHub Actions가 자동으로 변경해 줄 것입니다.
        image: docker.dev.westkite.dev/my-apps/nextjs-app:initial
        ports:
        - containerPort: 3000